This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file /Users/adminlocal/Resilio Sync/Uni/5.Semester/Studentische_Arbeiten_am_Lehrstuhl_Organic_Computing-New_documents/Abschlussarbeit Latex Vorlage/.texpadtmp/Main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/adminlocal/Resilio Sync/Uni/5.Semester/Studentische_Arbeiten_am_Lehrstuhl_Organic_Computing-New_documents/Abschlussarbeit Latex Vorlage/.texpadtmp/Main.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file /Users/adminlocal/Resilio Sync/Uni/5.Semester/Studentische_Arbeiten_am_Lehrstuhl_Organic_Computing-New_documents/Abschlussarbeit Latex Vorlage/.texpadtmp/Main.acr....done (9 lines written, 0 warnings).
Output written in /Users/adminlocal/Resilio Sync/Uni/5.Semester/Studentische_Arbeiten_am_Lehrstuhl_Organic_Computing-New_documents/Abschlussarbeit Latex Vorlage/.texpadtmp/Main.acr.
Transcript written in /Users/adminlocal/Resilio Sync/Uni/5.Semester/Studentische_Arbeiten_am_Lehrstuhl_Organic_Computing-New_documents/Abschlussarbeit Latex Vorlage/.texpadtmp/Main.alg.
